name: Cache Docker and Maven Dependencies

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cache-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository  # Путь к локальному Maven репозиторию
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Cache Docker images
        id: cache-docker
        uses: actions/cache@v3
        with:
          path: /tmp/.docker-image-cache
          key: ${{ runner.os }}-docker-cache-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-cache-
