name: Setup Selenium

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  setup-selenium:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: >-
          --health-cmd "curl -f http://localhost:4444/wd/hub/status || exit 1"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Wait for Selenium to be ready
        run: |
          echo "Waiting for Selenium to be ready..."
          sleep 15
