name: Run Selenium Tests with Selenoid

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  selenoid-tests:
    runs-on: ubuntu-latest

    services:
      # Запуск контейнера Selenoid
      selenoid:
        image: selenoid/selenoid:latest
        ports:
          - 4444:4444
        options: >-
          --health-cmd "curl -f http://localhost:4444/status || exit 1"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 10

      # Скачивание и запуск контейнеров для браузеров (например, Chrome)
      chrome:
        image: selenoid/chrome:latest
        ports:
          - 4444:4444
        options: >-
          --health-cmd "curl -f http://localhost:4444/wd/hub/status || exit 1"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Wait for Selenoid to be ready
        run: |
          echo "Waiting for Selenoid to be ready..."
          sleep 15

      - name: Run tests with Maven
        run: mvn clean test
        env:
          SELENIDE_REMOTE: http://localhost:4444/wd/hub
