name: Run Selenium Tests with Video

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  selenide-tests:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: >-
          --health-cmd "curl -f http://localhost:4444/wd/hub/status || exit 1"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Шаг для кэширования Docker образов
      - name: Cache Docker images
        id: cache-docker
        uses: actions/cache@v3
        with:
          path: /tmp/.docker-image-cache
          key: ${{ runner.os }}-docker-cache-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-cache-

      # Если кэшированного образа нет, то загружаем заново
      - name: Pull Selenium Docker image
        run: |
          if [ ! -f /tmp/.docker-image-cache/selenium/standalone-chrome ]; then
            docker pull selenium/standalone-chrome:latest
            mkdir -p /tmp/.docker-image-cache/selenium
            touch /tmp/.docker-image-cache/selenium/standalone-chrome
          fi

      - name: Wait for Selenium to be ready
        run: |
          echo "Waiting for Selenium to be ready..."
          sleep 15

      - name: Run tests with Maven
        run: mvn clean test
        env:
          SELENIDE_REMOTE: http://localhost:4444/wd/hub

      - name: Upload test videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: selenoid-videos
          path: ./selenoid/video/*.mp4

      - name: Echo link to video artifact
        if: always()
        run: |
          echo "🎥 Видео с теста можно скачать здесь:"
          echo "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
