name: Run Selenium Tests with Video

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Create browsers.json
        run: |
          mkdir -p config
          cat <<EOF > config/browsers.json
          {
            "chrome": {
              "default": "116.0",
              "versions": {
                "116.0": {
                  "image": "selenoid/chrome:116.0",
                  "port": "4444",
                  "path": "/"
                }
              }
            }
          }

      - name: Pull and run Selenoid
        run: |
          docker pull aerokube/selenoid:latest-release
          docker pull selenoid/chrome:116.0
          docker pull selenoid/video-recorder:latest-release

          docker network create selenoid || true

          docker run -d --name selenoid \
            --network selenoid \
            -p 4444:4444 \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v ${{ github.workspace }}/config:/etc/selenoid/:ro \
            -v ${{ github.workspace }}/video:/opt/selenoid/video \
            -e OVERRIDE_VIDEO_OUTPUT_DIR=true \
            -e ENABLE_VIDEO=true \
            aerokube/selenoid:latest-release

      - name: Wait for Selenoid to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:4444/status | grep -q '"total":'; then
              echo "Selenoid is ready!"
              exit 0
            fi
            echo "Waiting for Selenoid to be ready ($i/30)..."
            sleep 1
          done
          echo "Selenoid did not become ready in time!"
          exit 1

      - name: Run Tests with Maven
        run: |
          mvn clean test -Dselenide.remote=http://localhost:4444/wd/hub -Dselenide.browser=chrome

      - name: Upload videos
        uses: actions/upload-artifact@v4
        with:
          name: test-videos
          path: ./video/*.mp4
