name: Run Selenium Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cache-dependencies:
    uses: ./.github/workflows/ci-cache.yml
    with:
    # Здесь можно указать переменные, если они нужны для ci-cache.yml

  setup-selenium:
    needs: cache-dependencies
    uses: ./.github/workflows/ci-selenium.yml
    with:
    # Здесь можно указать переменные, если они нужны для ci-selenium.yml

  run-tests:
    needs: setup-selenium
    uses: ./.github/workflows/ci-tests.yml
    with:
    # Здесь можно указать переменные, если они нужны для ci-tests.yml
