name: Run Selenium Tests with Video

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  selenide-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Кэширование Maven зависимостей
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository  # Путь к локальному Maven репозиторию
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}  # Уникальный ключ для кэширования
          restore-keys: |
            ${{ runner.os }}-maven-

      # Кэширование Docker-образа Selenium
      - name: Cache selenium Docker image
        uses: actions/cache@v3
        with:
          path: /tmp/selenium-image.tar.gz
          key: selenium-image-${{ runner.os }}-${{ hashFiles('**/selenium-image.tar.gz') }}
          restore-keys: |
            selenium-image-${{ runner.os }}-

      # Скачивание и кэширование Docker-образа Selenium
      - name: Pull selenium Docker image if not cached
        run: |
          if [ ! -f /tmp/selenium-image.tar.gz ]; then
            docker pull selenium/standalone-chrome:latest
            docker save selenium/standalone-chrome:latest | gzip > /tmp/selenium-image.tar.gz
          fi

      # Загружаем кэшированный Docker-образ
      - name: Load selenium Docker image from cache
        run: |
          if [ -f /tmp/selenium-image.tar.gz ]; then
            docker load < /tmp/selenium-image.tar.gz
          fi

      # Сервис Selenium
      - name: Start Selenium service container
        run: |
          docker run -d -p 4444:4444 selenium/standalone-chrome:latest
          # Можно добавить задержку, чтобы сервис полностью поднялся
          echo "Waiting for Selenium to be ready..."
          sleep 15

      # Запуск тестов с Maven
      - name: Run tests with Maven
        run: mvn clean test
        env:
          SELENIDE_REMOTE: http://localhost:4444/wd/hub
