name: Run UI Tests in Docker with FFMPEG

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build --no-cache -t ui-tests-image .

      - name: Run tests inside Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            ui-tests-image

      - name: Archive videos
        run: |
          cd target/videos || exit 0
          zip -r ../../ui-test-videos.zip .
        if: always()

      - name: Upload video artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-videos
          path: ui-test-videos.zip
        if: always()
