name: Run UI Tests with Chrome, FFMPEG, and Xvfb

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build --no-cache -t ui-tests-image .

      - name: Run tests in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            ui-tests-image

      - name: Archive videos
        run: |
          if [ -d target/video ]; then
            zip -r target-videos.zip target/video
          else
            echo "No videos found."
          fi
        if: always()

      - name: Upload video artifact
        uses: actions/upload-artifact@v4
        if: always() && hashFiles('target-videos.zip') != ''
        with:
          name: ui-test-videos
          path: target-videos.zip

      - name: Upload target folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-videos
          path: target.zip
        if: always()
