name: Run UI Tests in Docker with FFMPEG

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image without cache
        run: docker build --no-cache -t ui-tests-image -f Dockerfile .

      - name: Start virtual display
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          export DISPLAY=:99

      - name: Run tests inside Docker
        run: |
          docker run --rm \
            -e DISPLAY=:99 \
            -v ${{ github.workspace }}:/app \
            ui-tests-image \
            mvn test \
              -Dvideo.folder=target\videos \
              -Dvideo.enabled=true \
              -Dvideo.mode=ALL \
              -Drecorder.type=FFMPEG \
              -Dvideo.save.mode=ALL \
              -Dsurefire.suiteXmlFiles=\app\src\test\resources\testng.xml
